site_name: SharingIsCaring
site_url: https://Leo.github.io/JustTry

theme:
  name: material
  palette: 
    - scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Project Info:
      - MVP: pbl/mvp.md
      - Database Schema: pbl/schema.md
  - Backend Team: 
      - Overview: pbl/backend/index.md
      - Details: pbl/backend/info.md
  - Frontend Team:
      - Overview: pbl/frontend/index.md
      - Details: pbl/frontend/info.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true